
package vista;

import excepciones.CargaInvalidaException;
import excepciones.DatoCargaInvalido;
import excepciones.FaltaCombustibleException;
import excepciones.TipoCombustibleInvalidoException;

import javax.swing.JOptionPane;

import paquete.Surtidor;

/**
 *
 * @author junio
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private Surtidor surtidor;

    /** Creates new form VistaPrincipal */
    public VistaPrincipal() {
        initComponents();
        this.surtidor = new Surtidor();
        this.actualizarVista();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        panelOpciones = new javax.swing.JPanel();
        panelCargar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtCombustible = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        paneLlenar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCombustibles = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOpciones.setLayout(new java.awt.GridLayout(2, 1));

        panelCargar.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Combustible:");
        jPanel3.add(jLabel1);

        panelCargar.add(jPanel3);

        txtCombustible.setColumns(10);
        jPanel5.add(txtCombustible);

        panelCargar.add(jPanel5);

        jLabel2.setText("Cantidad:");
        jPanel6.add(jLabel2);

        panelCargar.add(jPanel6);

        txtCantidad.setColumns(10);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel7.add(txtCantidad);

        panelCargar.add(jPanel7);
        panelCargar.add(jLabel3);

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel8.add(btnCargar);

        panelCargar.add(jPanel8);

        panelOpciones.add(panelCargar);

        paneLlenar.setLayout(new java.awt.GridLayout(0, 1));

        jButton1.setText("Llenar Premium");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        paneLlenar.add(jPanel2);

        jButton2.setText("Llenar Super");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        paneLlenar.add(jPanel4);

        jButton3.setText("Llenar Diesel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);

        paneLlenar.add(jPanel9);

        panelOpciones.add(paneLlenar);

        getContentPane().add(panelOpciones, java.awt.BorderLayout.EAST);

        txtAreaCombustibles.setColumns(20);
        txtAreaCombustibles.setRows(5);
        jScrollPane1.setViewportView(txtAreaCombustibles);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        try{
            double cantidad = Double.parseDouble(this.txtCantidad.getText().trim());
            String combustible = this.txtCombustible.getText().trim();
            this.surtidor.cargarCombustible(combustible, cantidad);
            this.actualizarVista();
        } catch (TipoCombustibleInvalidoException e) {
            DatoCargaInvalido dato = e.getDatoCargaInvalido();
            String msj= "Error de tipo de combustible. "+dato.getCombustible()+" invalido.";
            JOptionPane.showMessageDialog(this, msj, "Combustible Invalido", JOptionPane.ERROR_MESSAGE);
        } catch (FaltaCombustibleException e){
            this.actualizarVista();
            DatoCargaInvalido dato = e.getDatoCargaInvalido();
            String msj= "Error de falta de combustible. \n"
                        +dato.getCombustible()+" se tiene "+dato.getCantidaDisponible()+".\n"
                +" se requiere: "+dato.getCantidadRequerida()+".\n";
            JOptionPane.showMessageDialog(this, msj, "Falta combustible", JOptionPane.ERROR_MESSAGE);
        }catch (CargaInvalidaException e) {
            DatoCargaInvalido dato = e.getDatoCargaInvalido();
            String msj= "Error cantidad de combustible. "+dato.getCantidadRequerida()+" invalido.";
            JOptionPane.showMessageDialog(this, msj, "Cantidad Invalida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.surtidor.llenarPremium();
        this.actualizarVista();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.surtidor.llenarSuper();
        this.actualizarVista();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.surtidor.llenarDiesel();
        this.actualizarVista();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void actualizarVista(){
        this.txtAreaCombustibles.setText(this.surtidor.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneLlenar;
    private javax.swing.JPanel panelCargar;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextArea txtAreaCombustibles;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCombustible;
    // End of variables declaration//GEN-END:variables

}
