
package vista;

import excepciones.DatoInvalido;
import excepciones.DepositoInvalidoException;
import excepciones.ExtraccionInvalidadException;
import excepciones.TitularInvalidoException;

import javax.swing.JOptionPane;

import paquete.CuentaBancaria;
/**
 *
 * @author Junior
 */
public class VistaPrincipal extends javax.swing.JFrame {
    @SuppressWarnings("compatibility:-8883971470910450998")
    private static final long serialVersionUID = 1L;
    private CuentaBancaria cuenta;

    /** Creates new form VistaPrincipla */
    public VistaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        panelOpciones = new javax.swing.JPanel();
        panelCrear = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTitular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        panelAcciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDepositar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnExtraer = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtADetalle = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOpciones.setLayout(new java.awt.GridLayout(2, 1));

        panelCrear.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Titular: ");
        jPanel4.add(jLabel1);

        panelCrear.add(jPanel4);

        txtTitular.setColumns(10);
        txtTitular.setName("txtTitular"); // NOI18N
        jPanel3.add(txtTitular);

        panelCrear.add(jPanel3);
        panelCrear.add(jLabel2);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel5.add(btnCrear);

        panelCrear.add(jPanel5);

        panelOpciones.add(panelCrear);

        panelAcciones.setLayout(new java.awt.GridLayout(0, 1));

        txtCantidad.setColumns(10);
        jPanel1.add(txtCantidad);

        panelAcciones.add(jPanel1);

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        jPanel2.add(btnDepositar);

        panelAcciones.add(jPanel2);

        btnExtraer.setText("Extraer");
        btnExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraerActionPerformed(evt);
            }
        });
        jPanel6.add(btnExtraer);

        panelAcciones.add(jPanel6);

        panelOpciones.add(panelAcciones);

        getContentPane().add(panelOpciones, java.awt.BorderLayout.EAST);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel7.add(jScrollPane1);

        txtADetalle.setColumns(20);
        txtADetalle.setRows(5);
        txtADetalle.setTabSize(4);
        jScrollPane3.setViewportView(txtADetalle);

        jPanel7.add(jScrollPane3);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String titular = this.txtTitular.getText().trim();
        try {
            cuenta = new CuentaBancaria(titular);
            this.txtDescripcion.append("\nCuenta creada con exito.\n");
            this.actualizarVista();
        } catch (TitularInvalidoException e) {
            this.txtDescripcion.append("\n"+e.getMessage()+"\n");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        double cantidad = Double.parseDouble(this.txtCantidad.getText().trim());
        try {
            cuenta.depositar(cantidad);
            this.txtDescripcion.append("\nDeposito exitoso.\n");
            this.actualizarVista();
        } catch (DepositoInvalidoException e) {
            this.txtDescripcion.append("\n"+e.getMessage()+"\n");
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraerActionPerformed
        double cantidad = Double.parseDouble(this.txtCantidad.getText().trim());
        try {
            cuenta.extraer(cantidad);
            this.txtDescripcion.append("\nExtraccion exitosa.\n");
            this.actualizarVista();
        } catch (ExtraccionInvalidadException e) {
            DatoInvalido dato=e.getDato();
            String msg= "Erro al extraer: "+e.getMessage()+"\n Solicitado: "+dato.getExtraccion_solicitada()+
                        "\nSaldo disponible: "+dato.getSaldo();
            JOptionPane.showMessageDialog(this, msg, "Extraccion Invalida", JOptionPane.ERROR_MESSAGE);
            this.txtDescripcion.append("\n"+e.getMessage()+"\n");
        }
    }//GEN-LAST:event_btnExtraerActionPerformed

    public void actualizarVista(){
        this.txtADetalle.setText(this.cuenta.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExtraer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextArea txtADetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables

}
